steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/afroid-506916/afroid-containers/web:synced1', '-f', 'apps/web/Dockerfile', '.']
images: ['us-central1-docker.pkg.dev/afroid-506916/afroid-containers/web:synced1']
