"""CodeGen Service — Archetype Jinja2 Templates."""

from __future__ import annotations

FASTAPI_MAIN_TEMPLATE = """# Generated by Afroid geezcodE
from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

class HealthResponse(BaseModel):
    status: str = "healthy"
    service: str = "{{ service_name }}"

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup resources
    yield
    # Cleanup resources

app = FastAPI(
    title="{{ project_name }} API",
    description="{{ description }}",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/health", response_model=HealthResponse)
async def health():
    return HealthResponse()

{% for route in routes %}
@app.{{ route.method.lower() }}("{{ route.path }}")
async def {{ route.handler_name }}():
    \"\"\"{{ route.description }}\"\"\"
    return {"message": "Endpoint {{ route.path }} active"}
{% endfor %}
"""

DOCKERFILE_TEMPLATE = """# Generated by Afroid geezcodE
FROM python:3.12-slim AS builder

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends gcc && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt

FROM python:3.12-slim AS runtime
WORKDIR /app
COPY --from=builder /root/.local /root/.local
COPY . .
ENV PATH=/root/.local/bin:$PATH

RUN useradd -m appuser && chown -R appuser /app
USER appuser

EXPOSE {{ port | default(8000) }}
CMD ["uvicorn", "{{ entrypoint | default('main:app') }}", "--host", "0.0.0.0", "--port", "{{ port | default('8000') }}"]
"""

DOCKER_COMPOSE_TEMPLATE = """# Generated by Afroid geezcodE
version: "3.8"

services:
  app:
    build: .
    ports:
      - "{{ port | default(8000) }}:{{ port | default(8000) }}"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/{{ project_name | default('app') }}
      - ENVIRONMENT=development
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: {{ project_name | default('app') }}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
"""
